### ISSUE TITLE
Feature: Add AI Satsana to every minigame for feedback

### ISSUE THREAD

**Issue by ceh-2000** [ceh-2000/game-design-team-4#87]
ACTION = pressed key
CURRENT_STATE = “MENU/CUTSCENE/MINIGAME[1-4]”
RESULT = “PERFECT/ALMOST/MISS”

FRIEND_PERFECT = “Perfect!”
FRIEND_ALMOST = “Almost!”
FRIEND_MISS = “Try again!”

CUSTOMER_PERFECT = “Looks great!”
CUSTOMER_ALMOST = “Not too bad.”
CUSTOMER_MISS = “Are you doing that right?”

CRITIC_PERFECT = “Textbook!”
CRITIC_ALMOST = “Interesting way of doing that.”
CRITIC_MISS = “My readers will hear about this!”

PRO_PERFECT = “Amazing!”
PRO_ALMOST = “I could do better!”
PRO_MISS = “This is a disaster!”

**Comment by willkinney** [comment]
Done
